-- Feishu public-document post collection audit tables.
-- This migration is independent from yj_post and is safe to run before a dry run.

CREATE TABLE IF NOT EXISTS `yj_feishu_post_collection_run` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '采集运行编号',
  `task_id` bigint DEFAULT NULL COMMENT '岗位采集任务编号',
  `folder_token` varchar(128) NOT NULL COMMENT '飞书目录标识',
  `status` varchar(32) NOT NULL COMMENT '运行状态：DRY_RUN/RUNNING/SUCCESS/PARTIAL_FAILED/FAILED',
  `documents_seen` int NOT NULL DEFAULT 0 COMMENT '发现文档数',
  `documents_processed` int NOT NULL DEFAULT 0 COMMENT '处理文档数',
  `documents_failed` int NOT NULL DEFAULT 0 COMMENT '失败文档数',
  `jobs_extracted` int NOT NULL DEFAULT 0 COMMENT '解析岗位数',
  `jobs_created` int NOT NULL DEFAULT 0 COMMENT '新增岗位数',
  `jobs_updated` int NOT NULL DEFAULT 0 COMMENT '更新岗位数',
  `jobs_skipped` int NOT NULL DEFAULT 0 COMMENT '跳过岗位数',
  `jobs_failed` int NOT NULL DEFAULT 0 COMMENT '失败岗位数',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '脱敏错误信息',
  `started_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
  `finished_at` datetime DEFAULT NULL COMMENT '完成时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_yj_feishu_run_folder_time` (`folder_token`, `started_at`),
  KEY `idx_yj_feishu_run_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='飞书岗位采集运行审计';

CREATE TABLE IF NOT EXISTS `yj_feishu_post_document` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文档同步编号',
  `folder_token` varchar(128) NOT NULL COMMENT '飞书目录标识',
  `document_id` varchar(128) NOT NULL COMMENT '飞书文档标识',
  `document_name` varchar(255) NOT NULL COMMENT '文档名称',
  `document_url` varchar(500) NOT NULL COMMENT '文档地址',
  `document_revision_id` varchar(128) DEFAULT NULL COMMENT '文档版本或内容版本',
  `content_hash` char(64) DEFAULT NULL COMMENT '正文 SHA-256',
  `collected` bit(1) NOT NULL DEFAULT b'0' COMMENT '当前版本是否已完成采集',
  `status` varchar(32) NOT NULL DEFAULT 'NEW' COMMENT 'NEW/PROCESSING/NO_JOBS/COLLECTED/PARTIAL_FAILED/FAILED/SKIPPED',
  `last_run_id` bigint DEFAULT NULL COMMENT '最近运行编号',
  `last_error` varchar(1000) DEFAULT NULL COMMENT '脱敏错误信息',
  `extracted_count` int NOT NULL DEFAULT 0 COMMENT '最近解析岗位数',
  `created_count` int NOT NULL DEFAULT 0 COMMENT '最近新增岗位数',
  `updated_count` int NOT NULL DEFAULT 0 COMMENT '最近更新岗位数',
  `skipped_count` int NOT NULL DEFAULT 0 COMMENT '最近跳过岗位数',
  `failed_count` int NOT NULL DEFAULT 0 COMMENT '最近失败岗位数',
  `collected_at` datetime DEFAULT NULL COMMENT '完成采集时间',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_yj_feishu_document` (`folder_token`, `document_id`),
  KEY `idx_yj_feishu_document_status` (`status`, `collected`),
  KEY `idx_yj_feishu_document_run` (`last_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='飞书岗位文档同步状态';

CREATE TABLE IF NOT EXISTS `yj_feishu_post_document_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '文档岗位明细编号',
  `run_id` bigint NOT NULL COMMENT '采集运行编号',
  `document_id` bigint NOT NULL COMMENT '文档同步编号',
  `item_index` int NOT NULL COMMENT '文档内岗位序号',
  `source_text` text COMMENT '岗位原文片段',
  `ai_raw_json` text COMMENT 'AI 原始岗位 JSON',
  `name` varchar(100) DEFAULT NULL COMMENT '岗位名称',
  `company_name` varchar(100) DEFAULT NULL COMMENT '企业名称',
  `source_code` varchar(20) DEFAULT NULL COMMENT '来源编码',
  `external_post_id` varchar(100) DEFAULT NULL COMMENT '外部岗位标识',
  `salary_range` varchar(100) DEFAULT NULL COMMENT '薪资范围',
  `work_area` varchar(100) DEFAULT NULL COMMENT '工作区域',
  `publish_date` varchar(20) DEFAULT NULL COMMENT '发布时间',
  `detail_url` varchar(500) DEFAULT NULL COMMENT '岗位详情地址',
  `target_post_id` bigint DEFAULT NULL COMMENT '正式岗位编号',
  `status` varchar(32) NOT NULL DEFAULT 'EXTRACTED' COMMENT 'EXTRACTED/CREATED/UPDATED/SKIPPED/FAILED',
  `error_message` varchar(1000) DEFAULT NULL COMMENT '脱敏错误信息',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_yj_feishu_document_item_run_index` (`run_id`, `document_id`, `item_index`),
  KEY `idx_yj_feishu_item_status` (`run_id`, `status`),
  KEY `idx_yj_feishu_item_external` (`source_code`, `external_post_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='飞书岗位 AI 解析与入库明细';
