services:
  neo4j:
    image: neo4j:latest
    container_name: remote-replay-neo4j
    ports:
      - "7476:7474"
      - "7688:7687"
    environment:
      NEO4J_AUTH: none
      NEO4J_server_default__listen__address: "0.0.0.0"
      NEO4J_server_default__advertised__address: "localhost"
      NEO4J_server_bolt_advertised__address: "localhost:7688"
      NEO4J_server_http_advertised__address: "localhost:7476"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
